# This workflow will run tests using node and then publish a package to NPM Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Main Build

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-18.04
    env:
      EVENT_TYPE: main-deploy
      VERSION: latest
      NS: devops-test-uat
      IMAGE_ORG_NAME: 36node
      IMAGE_REPO_NAME: devops-backend-test
      DEVOPS_ORG_NAME: cc3630
      DEVOPS_REPO_NAME: cc-devops-test
      ORG_NAME: cc3630
      REPO_NAME: devops-backend-test
    steps:
      - uses: actions/checkout@v2
      - name: Login aliyun
        uses: aliyun/acr-login@v1
        with:
          login-server: "${{ secrets.ALI_REGISTRY }}"
          username: "${{ secrets.ALI_USERNAME }}"
          password: "${{ secrets.ALI_PASSWORD }}"
      - name: Build and push image
        env:
          SERVER: ${{ secrets.ALI_REGISTRY }}
        run: |
          docker build -t $SERVER/$IMAGE_ORG_NAME/$IMAGE_REPO_NAME:$VERSION .
          docker push $SERVER/$IMAGE_ORG_NAME/$IMAGE_REPO_NAME:$VERSION
      - name: Create repository dispatch event
        env:
          URL: https://api.github.com/repos/${{ env.DEVOPS_ORG_NAME }}/${{ env.DEVOPS_REPO_NAME }}/dispatches
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ env.URL }}
          method: "POST"
          customHeaders: '{"Accept":"application/vnd.github.v3+json","Authorization":"token ${{ secrets.PR_TOKEN }}"}'
          data: '{"event_type":"${{ env.EVENT_TYPE }}","client_payload":{"namespace":"${{ env.NS }}","owner":"${{ env.ORG_NAME }}","image_org":"${{ env.IMAGE_ORG_NAME }}","image_repo":"${{ env.IMAGE_REPO_NAME }}","org":"${{ env.REPO_NAME }}","repo":"${{ env.REPO_NAME }}","tag":"${{ env.VERSION }}"}}'
