# This workflow will run tests using node and then publish a package to NPM Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: pr build image

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-18.04
    env:
      ORG_NAME: 36node
      REPO_NAME: devops-backend-test
    steps:
      - uses: actions/checkout@v2
      - name: Create repository dispatch event
        env:
          URL: https://api.github.com/repos/cc3630/cc-devops-test/dispatches
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ env.URL }}
          method: "POST"
          customHeaders: '{"Accept":"application/vnd.github.v3+json","Authorization":"token ${{ secrets.PR_TOKEN }}"}'
          data: '{"event_type":"custom_event_type","client_payload":{"owner":"${{ env.ORG_NAME }}","repo":"${{ env.REPO_NAME }}","tag":"pr-4"}}'
